apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values "config-service" "rest" }}
  labels:
    app: {{ index .Values "config-service" "rest" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.restcontainerPort }}
      targetPort: {{ .Values.service.resttargerPort }}
  selector:
    app: {{ index .Values "config-service" "app" }}