apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "provisioning-service.name" . }}
  labels:
    app: {{ include "provisioning-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "provisioning-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "provisioning-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: APPCONTEXT
            value: {{ .Values.provisioning-service.env }}
          ports:
          - containerPort: {{ .Values.service.containerPort }}
          volumeMounts:
          - name: {{ .Values.configmap.volumename }}
            mountPath: {{ .Values.configmap.mountPath }}
            readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ .Values.configmap.volumename }}
        configMap:
          name: {{ .Values.configmap.name }}
          defaultMode: 0700
