version: '3'
services:
  reverse-proxy:
    image: vmwblockchain/reverse-proxy:latest
    ports:
      - "443:443"
      - "8843:8843"
    volumes:
      - ./docker/data/nginx/docker-compose.conf.d:/etc/nginx/conf.d

  fluentd:
    build:
      context: ./docker/fluentd
    image: "${fluentd_repo}:${fluentd_tag}"
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes:
      - ./docker/fluentd:/fluentd/etc
