version: '3'
services:
  concord1:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    command: /bin/bash -c "
      cp /concord/config-local/concord_with_hostnames.config
         /concord/config-local/concord.config &&
      /concord/config-public/find-docker-instances.sh &&
      /concord/concord -c /concord/config-local/concord.config"
    expose:
      - 5458
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    ports:
      - 5458:5458
    volumes:
      - ./devdata/rocksdbdata1:/concord/rocksdbdata
      - ./devdata/log1:/concord/log
      - ./docker/config-concord1:/concord/config-local
      - ./docker/config-public:/concord/config-public:ro
      - ${tls_certs_location}:/concord/tls_certs:ro

  concord2:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    command: /bin/bash -c "
      cp /concord/config-local/concord_with_hostnames.config
         /concord/config-local/concord.config &&
      /concord/config-public/find-docker-instances.sh &&
      /concord/concord -c /concord/config-local/concord.config"
    expose:
      - 5458
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    ports:
      - 5459:5458
    volumes:
      - ./devdata/rocksdbdata2:/concord/rocksdbdata
      - ./devdata/log2:/concord/log
      - ./docker/config-concord2:/concord/config-local
      - ./docker/config-public:/concord/config-public:ro
      - ${tls_certs_location}:/concord/tls_certs:ro

  concord3:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    command: /bin/bash -c "
      cp /concord/config-local/concord_with_hostnames.config
         /concord/config-local/concord.config &&
      /concord/config-public/find-docker-instances.sh &&
      /concord/concord -c /concord/config-local/concord.config"
    expose:
      - 5458
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    ports:
      - 5460:5458
    volumes:
      - ./devdata/rocksdbdata3:/concord/rocksdbdata
      - ./devdata/log3:/concord/log
      - ./docker/config-concord3:/concord/config-local
      - ./docker/config-public:/concord/config-public:ro
      - ${tls_certs_location}:/concord/tls_certs:ro

  concord4:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    command: /bin/bash -c "
      cp /concord/config-local/concord_with_hostnames.config
         /concord/config-local/concord.config &&
      /concord/config-public/find-docker-instances.sh &&
      /concord/concord -c /concord/config-local/concord.config"
    expose:
      - 5458
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    ports:
      - 5461:5458
    volumes:
      - ./devdata/rocksdbdata4:/concord/rocksdbdata
      - ./devdata/log4:/concord/log
      - ./docker/config-concord4:/concord/config-local
      - ./docker/config-public:/concord/config-public:ro
      - ${tls_certs_location}:/concord/tls_certs:ro
