version: '3'
services:
  db-server:
    image: cockroachdb/cockroach:v2.0.2
    ports:
      - 26257:26257
    volumes:
      - ./devdata/cockroachDB:/cockroach/cockroach-data
    command:
      - start
      - --insecure

  db-server-init1:
    image: cockroachdb/cockroach:v2.0.2
    command: --host db-server user set helen_admin --insecure
    depends_on:
      - db-server

  db-server-init2:
    image: cockroachdb/cockroach:v2.0.2
    volumes:
      - ./helen/src/main/resources/database:/cockroach/resources
    entrypoint: sh -c "./cockroach --host db-server sql --insecure < /cockroach/resources/schema.sql"
    depends_on:
      - db-server-init1
