version: '3'
services:
  concord1:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata1:/concord/rocksdbdata
      - ./log1:/concord/log
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro

# This is an example of what ConcordRpcUrls in helen's
# application.properties refers to. If you have an ethrpc image
# available, you can uncomment this block to use it.
#  ethrpc1:
#    image: "${ethrpc_repo}:${ethrpc_tag}"
#    ports:
#      - 8545:8545
#    command:
#      - java
#      - -jar
#      - concord-ethrpc-1.0-SNAPSHOT.jar
#      - --ConcordAuthorities=concord1:5458

  concord2:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata2:/concord/rocksdbdata
      - ./log2:/concord/log
      - ./config-concord2:/concord/config-local
      - ./config-public:/concord/config-public:ro

  concord3:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata3:/concord/rocksdbdata
      - ./log3:/concord/log
      - ./config-concord3:/concord/config-local
      - ./config-public:/concord/config-public:ro

  concord4:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata4:/concord/rocksdbdata
      - ./log4:/concord/log
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro

  helen:
    image: "${helen_repo}:${helen_tag}"
    ports:
      - 8080:8080
    depends_on:
      - db-server
    # Used for sending logs to log intelligence
    # We don't want this on by default, because logs won't be available locally for debugging
    # You will need to add the log intelligence in the fluent.conf file for it to work.
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     tag: httpd.access

  ui:
    build:
      context: ../../ui
    image: "${ui_repo}:${ui_tag}"
    ports:
      - 80:80
    depends_on:
      - helen

  db-server:
    image: cockroachdb/cockroach:v2.0.2
    ports:
      - 26257:26257
    volumes:
      - ./cockroachDB:/cockroach/cockroach-data
    command:
      - start
      - --insecure

  reverse-proxy:
    image: vmwblockchain/reverse-proxy:latest
    ports:
      - "443:443"
      - "8843:8843"
    volumes:
      - ./data/nginx/docker-compose.conf.d:/etc/nginx/conf.d
    depends_on:
      - helen

  fluentd:
    build:
      context: ./fluentd
    image: "${fluentd_repo}:${fluentd_tag}"
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - FLUENTD_CONF=fluentd.conf
    volumes:
      - ./fluentd:/fluentd/etc
