version: '3'
services:
  concord1:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata1:/concord/rocksdbdata
      - ./log1:/concord/log
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro

  ethrpc1:
    image: "${ethrpc_repo}:${ethrpc_tag}"
    ports:
      - 8545:8545
    volumes:
      - ./config-ethrpc1:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord1:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc

  concord2:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata2:/concord/rocksdbdata
      - ./log2:/concord/log
      - ./config-concord2:/concord/config-local
      - ./config-public:/concord/config-public:ro

  ethrpc2:
    image: "${ethrpc_repo}:${ethrpc_tag}"
    ports:
      - 8546:8545
    volumes:
      - ./config-ethrpc2:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord2:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc

  concord3:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata3:/concord/rocksdbdata
      - ./log3:/concord/log
      - ./config-concord3:/concord/config-local
      - ./config-public:/concord/config-public:ro

  ethrpc3:
    image: "${ethrpc_repo}:${ethrpc_tag}"
    ports:
      - 8547:8545
    volumes:
      - ./config-ethrpc3:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord3:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc

  concord4:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata4:/concord/rocksdbdata
      - ./log4:/concord/log
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro

  ethrpc4:
    image: "${ethrpc_repo}:${ethrpc_tag}"
    ports:
      - 8548:8545
    volumes:
      - ./config-ethrpc4:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord4:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc

  helen:
    image: "${helen_repo}:${helen_tag}"
    ports:
      - 8080:8080
    depends_on:
      - db-server
    volumes:
      - ./config-helen:/config:ro
    # Used for sending logs to log intelligence
    # We don't want this on by default, because logs won't be available locally for debugging
    # You will need to add the log intelligence in the fluent.conf file for it to work.
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     tag: httpd.access

  ui:
    build:
      context: ../../ui
    image: "${ui_repo}:${ui_tag}"
    ports:
      - 80:80
    depends_on:
      - helen

  db-server:
    image: cockroachdb/cockroach:v2.0.2
    ports:
      - 26257:26257
    volumes:
      - ./cockroachDB:/cockroach/cockroach-data
    command:
      - start
      - --insecure

  reverse-proxy:
    image: athena-docker-local.artifactory.eng.vmware.com/reverse-proxy:0.1.2
    ports:
      - "443:443"
      - "8843:8843"
    volumes:
      - ./data/nginx/docker-compose.conf.d:/etc/nginx/conf.d
    depends_on:
      - helen

  fluentd:
    build:
      context: ./fluentd
    image: "${fluentd_repo}:${fluentd_tag}"
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - FLUENTD_CONF=fluentd.conf
    volumes:
      - ./fluentd:/fluentd/etc
