version: '3'
services:
  concord1:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata1:/concord/rocksdbdata
      - ./log1:/concord/log
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro

  concord2:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata2:/concord/rocksdbdata
      - ./log2:/concord/log
      - ./config-concord2:/concord/config-local
      - ./config-public:/concord/config-public:ro

  concord3:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata3:/concord/rocksdbdata
      - ./log3:/concord/log
      - ./config-concord3:/concord/config-local
      - ./config-public:/concord/config-public:ro

  concord4:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./rocksdbdata4:/concord/rocksdbdata
      - ./log4:/concord/log
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro

  helen:
    image: "${helen_repo}:${helen_tag}"
    ports:
      - 8080:8080
    depends_on:
      - db-server

  db-server:
    image: cockroachdb/cockroach:v2.0.2
    ports:
      - 26257:26257
    volumes:
      - ./cockroachDB:/cockroach/cockroach-data
    command:
      - start
      - --insecure

  reverse-proxy:
    image: vmwblockchain/reverse-proxy:latest
    ports:
      - "443:443"
      - "8843:8843"
    volumes:
      - ./data/nginx/docker-compose.conf.d:/etc/nginx/conf.d
    depends_on:
      - helen
