apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contract-compiler.name" . }}
  labels:
    app: {{ template "contract-compiler.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ template "contract-compiler.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "contract-compiler.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.containerPort }}
