version: '3'
services:
  concord4:
    image: "vmwblockchain/concord-core:latest"
    ports:
      - 5458:5458
      - 3501:3501
      - 3502:3502
      - 3503:3503
      - 3504:3504
      - 3505:3505
    volumes:
      - ./devdata/rocksdbdata4:/concord/rocksdbdata
      - ./devdata/log4:/concord/log
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  ethrpc4:
    image: "vmwblockchain/ethrpc:latest"
    ports:
      - 8545:8545
    volumes:
      - ./config-ethrpc4:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord4:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc

