version: '3'
services:
  concord1:
    image: "vmwblockchain/concord-core:latest"
    command: /bin/bash -c "
      cp /concord/config-local/concord_with_hostnames.config
         /concord/config-local/concord.config &&
      /concord/config-public/find-docker-instances.sh &&
      /concord/concord -c /concord/config-local/concord.config"
    ports:
      - 5458:5458
      - 3501:3501
      - 3502:3502
      - 3503:3503
      - 3504:3504
      - 3505:3505
    volumes:
      - ./devdata/rocksdbdata1:/concord/rocksdbdata
      - ./devdata/log1:/concord/log
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  ethrpc1:
    image: "vmwblockchain/ethrpc:latest"
    ports:
      - 8545:8545
    volumes:
      - ./config-ethrpc1:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord1:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc

