version: '3'
services:
  helen:
    image: "vmwblockchain/concord-ui:latest"
    ports:
      - 8080:8080
    environment:
      - LINT_API_TOKEN=${LINT_API_TOKEN}
    depends_on:
      - db-server
    volumes:
      - ./config-helen:/config:ro
      - ./application.properties:/helen/application.properties
      - ./application-test.properties:/helen/application-test.properties
    # Used for sending logs to log intelligence
    # We don't want this on by default, because logs won't be available locally for debugging
    # You will need to add the log intelligence in the fluent.conf file for it to work.
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     tag: httpd.access

  db-server:
    image: cockroachdb/cockroach:v2.0.2
    ports:
      - 26257:26257
    volumes:
      - ./devdata/cockroachDB:/cockroach/cockroach-data
    command:
      - start
      - --insecure

  db-server-init1:
    image: cockroachdb/cockroach:v2.0.2
    command: --host db-server user set helen_admin --insecure
    depends_on:
      - db-server

  db-server-init2:
    image: cockroachdb/cockroach:v2.0.2
    volumes:
      - ./database:/cockroach/resources:ro
    entrypoint: sh -c "./cockroach --host db-server sql --insecure < /cockroach/resources/schema.sql"
    depends_on:
      - db-server-init1

