client_proxies_per_replica: 4
c_val: 0
f_val: 1
FEATURE_time_service: false
node__TEMPLATE:
  logger_config: /concord/config-local/log4cplus.properties
  genesis_block: /concord/config-public/genesis.json
  blockchain_db_path: /concord/rocksdbdata/
node:
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: concord1
    replica:
      - replica_host: concord1
        replica_port: 3501
    client_proxy:
      - client_host: concord1
        client_port: 3502
      - client_host: concord1
        client_port: 3503
      - client_host: concord1
        client_port: 3504
      - client_host: concord1
        client_port: 3505
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: concord2
    replica:
      - replica_host: concord2
        replica_port: 3501
    client_proxy:
      - client_host: concord2
        client_port: 3502
      - client_host: concord2
        client_port: 3503
      - client_host: concord2
        client_port: 3504
      - client_host: concord2
        client_port: 3505
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: concord3
    replica:
      - replica_host: concord3
        replica_port: 3501
    client_proxy:
      - client_host: concord3
        client_port: 3502
      - client_host: concord3
        client_port: 3503
      - client_host: concord3
        client_port: 3504
      - client_host: concord3
        client_port: 3505
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: concord4
    replica:
      - replica_host: concord4
        replica_port: 3501
    client_proxy:
      - client_host: concord4
        client_port: 3502
      - client_host: concord4
        client_port: 3503
      - client_host: concord4
        client_port: 3504
      - client_host: concord4
        client_port: 3505
