version: '3'
services:
  concord1:
    image: "${concord_repo}:${concord_tag}_memleak"
    volumes:
      - /tmp:/tmp
      - ./tls_certs:/concord/tls_certs:ro
  helen:
    command:
      - java
      - -Dspring.profiles.active=test
      - -jar
      - blockchain-helen.jar
      - --ConcordAuthorities=concord1:5458
