version: '3'

services:

  helen:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc1:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc2:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc3:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc4:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc
