version: '3'
services:
  # Note: Make sure that Concord's configuration files have `daml_enable` set
  concord1:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 50051
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata1:/concord/rocksdbdata
      - ./devdata/log1:/concord/log
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord2:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 50051
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata2:/concord/rocksdbdata
      - ./devdata/log2:/concord/log
      - ./config-concord2:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord3:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 50051
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata3:/concord/rocksdbdata
      - ./devdata/log3:/concord/log
      - ./config-concord3:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord4:
    image: "${concord_repo}:${concord_tag}"
    expose:
      - 50051
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata4:/concord/rocksdbdata
      - ./devdata/log4:/concord/log
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  daml_ledgerapi:
    # Pulls the first PoC aka gitlab.eng.vmware.com/bfink/daml-on-vmware
    image: "athena-docker-local.artifactory.eng.vmware.com/daml-ledgerapi:478f46d"
    links:
      - concord1
    expose:
      - 6865
