version: '3'

services:

  ethrpc1:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc2:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc3:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc4:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  concord1:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: concord

  concord2:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: concord

  concord3:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: concord

  concord4:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: concord
