version: '3'

services:

  fluentd:
    image: "${fluentd_repo}:${fluentd_tag}"
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
    environment:
      - LOG_DESTINATION=LOG_INTELLIGENCE
      - LINT_ENDPOINT_URL=https://data.mgmt.cloud.vmware.com/le-mans/v1/streams/ingestion-pipeline-stream
      - "LINT_AUTHORIZATION_BEARER=${LINT_AUTHORIZATION_BEARER}"
      - LOG_INSIGHT_HOST=10.78.20.10
      - LOG_INSIGHT_PORT=9000
      - LOG_INSIGHT_AGENT_ID=0
      - CONSORTIUM_ID=100
      - REPLICA_ID=1

  ethrpc1:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc2:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc3:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  ethrpc4:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: ethrpc

  concord1:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: concord

  concord2:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: concord

  concord3:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: concord

  concord4:
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: concord
