version: '3'
services:
  # Create test tool container
  daml_test_tool:
    image: athena-docker-local.artifactory.eng.vmware.com/daml-ledger-api-test-tool:100.13.16

  # Note: Make sure that Concord's configuration files have `daml_enable` set
  concord1:
    image: "${concord_repo}:${concord_tag}"
    depends_on:
      - daml_execution_engine1
    expose:
      - 50051
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata1:/concord/rocksdbdata
      - ./devdata/log1:/concord/log
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord2:
    image: "${concord_repo}:${concord_tag}"
    depends_on:
      - daml_execution_engine2
    expose:
      - 50051
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata2:/concord/rocksdbdata
      - ./devdata/log2:/concord/log
      - ./config-concord2:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord3:
    image: "${concord_repo}:${concord_tag}"
    depends_on:
      - daml_execution_engine3
    expose:
      - 50051
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata3:/concord/rocksdbdata
      - ./devdata/log3:/concord/log
      - ./config-concord3:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord4:
    image: "${concord_repo}:${concord_tag}"
    depends_on:
      - daml_execution_engine4
    expose:
      - 50051
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata4:/concord/rocksdbdata
      - ./devdata/log4:/concord/log
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  daml_ledger_api1:
    image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
    command: "/doc/daml/kvbc_ledger_server/target/universal/stage/bin/kvbc-ledger-server concord1:50051 daml_ledger_api1"
    depends_on:
      - concord1
    expose:
      - 6865
    ports:
      - "6861:6865"

  daml_ledger_api2:
    image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
    command: "/doc/daml/kvbc_ledger_server/target/universal/stage/bin/kvbc-ledger-server concord2:50051 daml_ledger_api2"
    depends_on:
      - concord2
    expose:
      - 6865
    ports:
      - "6862:6865"

  daml_ledger_api3:
    image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
    command: "/doc/daml/kvbc_ledger_server/target/universal/stage/bin/kvbc-ledger-server concord3:50051 daml_ledger_api3"
    depends_on:
      - concord3
    expose:
      - 6865
    ports:
      - "6863:6865"

  daml_ledger_api4:
    image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
    command: "/doc/daml/kvbc_ledger_server/target/universal/stage/bin/kvbc-ledger-server concord4:50051 daml_ledger_api4"
    depends_on:
      - concord4
    expose:
      - 6865
    ports:
      - "6864:6865"

  daml_execution_engine1:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    command: /doc/daml/kvbc_validator/target/universal/stage/bin/kvbc-validator
    expose:
      - 55000

  daml_execution_engine2:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    command: /doc/daml/kvbc_validator/target/universal/stage/bin/kvbc-validator
    expose:
      - 55000

  daml_execution_engine3:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    command: /doc/daml/kvbc_validator/target/universal/stage/bin/kvbc-validator
    expose:
      - 55000

  daml_execution_engine4:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    command: /doc/daml/kvbc_validator/target/universal/stage/bin/kvbc-validator
    expose:
      - 55000

  fluentd:
    image: "${fluentd_repo}:${fluentd_tag}"
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes:
      - ./fluentd:/fluentd/etc
