version: '3'
services:
  ethrpc1:
    image: "${ethrpc_repo}:${ethrpc_tag}"
    ports:
      - 8545:8545
    volumes:
      - ./config-ethrpc1:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord1:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc
