version: '3'
services:
  # Create test tool container
  daml_test_tool:
    image: athena-docker-local.artifactory.eng.vmware.com/daml-ledger-api-test-tool:100.13.16-java

  # Note: Make sure that Concord's configuration files have `daml_enable` set
  concord1:
    image: "${concord_repo}:${concord_tag}"
    depends_on:
      - daml_execution_engine1
    expose:
      - 50051
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata1:/concord/rocksdbdata
      - ./devdata/log1:/concord/log
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord2:
    image: "${concord_repo}:${concord_tag}"
    depends_on:
      - daml_execution_engine2
    expose:
      - 50051
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata2:/concord/rocksdbdata
      - ./devdata/log2:/concord/log
      - ./config-concord2:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord3:
    image: "${concord_repo}:${concord_tag}"
    depends_on:
      - daml_execution_engine3
    expose:
      - 50051
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata3:/concord/rocksdbdata
      - ./devdata/log3:/concord/log
      - ./config-concord3:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord4:
    image: "${concord_repo}:${concord_tag}"
    depends_on:
      - daml_execution_engine4
    expose:
      - 50051
      - 5458
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata4:/concord/rocksdbdata
      - ./devdata/log4:/concord/log
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  daml_ledger_api1:
    image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
    environment:
      - INDEXDB_HOST=index_db
      - INDEXDB_PORT=5432
      - INDEXDB_USER=indexdb
      - CONCORD_HOST=concord1
      - CONCORD_PORT=50051
      - PARTICIPANT_ID=daml_ledger_api1
    depends_on:
      - concord1
      - index_db
    expose:
      - 6865
    ports:
      - "6861:6865"

  daml_ledger_api2:
    image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
    environment:
      - INDEXDB_HOST=index_db
      - INDEXDB_PORT=5432
      - INDEXDB_USER=indexdb
      - CONCORD_HOST=concord2
      - CONCORD_PORT=50051
      - PARTICIPANT_ID=daml_ledger_api2
    depends_on:
      - concord2
      - index_db
    expose:
      - 6865
    ports:
      - "6862:6865"

  # daml_ledger_api3:
  #   image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
  #   environment:
  #     - INDEXDB_HOST=index_db
  #     - INDEXDB_PORT=5432
  #     - INDEXDB_USER=indexdb
  #     - CONCORD_HOST=concord3
  #     - CONCORD_PORT=50051
  #     - PARTICIPANT_ID=daml_ledger_api3
  #   depends_on:
  #     - concord3
  #     - index_db
  #   expose:
  #     - 6865
  #   ports:
  #     - "6863:6865"

  # daml_ledger_api4:
  #   image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
  #   environment:
  #     - INDEXDB_HOST=index_db
  #     - INDEXDB_PORT=5432
  #     - INDEXDB_USER=indexdb
  #     - CONCORD_HOST=concord4
  #     - CONCORD_PORT=50051
  #     - PARTICIPANT_ID=daml_ledger_api4
  #   depends_on:
  #     - concord4
  #     - index_db
  #   expose:
  #     - 6865
  #   ports:
  #     - "6864:6865"

  daml_execution_engine1:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    command: /doc/daml/kvbc_validator/target/universal/stage/bin/kvbc-validator
    depends_on:
      - fluentd
    expose:
      - 55000

  daml_execution_engine2:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    command: /doc/daml/kvbc_validator/target/universal/stage/bin/kvbc-validator
    depends_on:
      - fluentd
    expose:
      - 55000

  daml_execution_engine3:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    command: /doc/daml/kvbc_validator/target/universal/stage/bin/kvbc-validator
    depends_on:
      - fluentd
    expose:
      - 55000

  daml_execution_engine4:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    command: /doc/daml/kvbc_validator/target/universal/stage/bin/kvbc-validator
    depends_on:
      - fluentd
    expose:
      - 55000

  fluentd:
    image: "${fluentd_repo}:${fluentd_tag}"
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes:
      - ./fluentd:/fluentd/etc

  index_db:
    image: daml-postgres
    command: postgres -c 'max_connections=300' -c 'shared_buffers=80MB'
    restart: always
    environment:
      - POSTGRES_USER=indexdb
      - POSTGRES_MULTIPLE_DATABASES=daml_ledger_api1,daml_ledger_api2,daml_ledger_api3,daml_ledger_api4
    volumes:
      - ./devdata/index_db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"