type: google.api.Service
config_version: 3

http:
    rules:
    - selector: vmware.blockchain.deployment.v1.ConfigurationService.GetNodeConfiguration
      get: /v1/configurations/{identifier.identifier}/nodes/{node}
    - selector: vmware.blockchain.deployment.v1.ConfigurationService.GetNodeConfiguration
      post: /v1/configuration/node
      body: "*"
