apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: athena-docker-local.artifactory.eng.vmware.com/persephone-configuration:657
        ports:
        - containerPort: 9003
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /config/persephone/configuration/
          readOnly: true
        resources:
          requests:
            memory: "1024Mi"
            cpu: "512m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"
      imagePullSecrets:
        - name: bintray
      volumes:
      - name: config-volume
        configMap:
          name: config-service
          defaultMode: 0700
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  type: NodePort
  ports:
  - port: 9003
    nodePort: 30093
    name: config-service
  selector:
    app: config-service
