apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ipam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
    spec:
      containers:
      - name: ipam
        image: vmware-docker-blockchainsaas.bintray.io/ipam:test
        ports:
        - containerPort: 9099
        imagePullPolicy: Always
        volumeMounts:
        - name: ipam-volume
          mountPath: /config/persephone/ipam/
          readOnly: true
      imagePullSecrets:
        - name: bintray
      volumes:
      - name: ipam-volume
        configMap:
          name: ipam
          defaultMode: 0700
---
apiVersion: v1
kind: Service
metadata:
  name: ipam
  labels:
    app: ipam
spec:
  type: NodePort
  ports:
  - port: 9099
    nodePort: 30099
    name: ipam
  selector:
    app: ipam