apiVersion: v1
kind: Service
metadata:
  name: {{ include "helen.name" . }}
  labels:
    app: {{ template "helen.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "helen.name" . }}
    app.kubernetes.io/instance: {{ include "helen.name" . }}
