# Default values for contract-compiler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vmware-docker-blockchainsaas.bintray.io/vmwblockchain/contract-compiler
  tag: stable
  pullPolicy: Always
  pullSecret: bintray

service:
  type: ClusterIP
  containerPort: 3000
  targetPort: 3000
  terminationGracePeriod: 10
