version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - helen:${helen_ip}
  grafana:
    image: grafana/grafana
    ports:
      - 3010:3000
    depends_on:
      - prometheus