kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: staging
  namespace: vmbc-stg-saas
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
