---
simpleConfig:
  blockchain: concord
  environment: onprem
  nodeCount: 4
  port: 8545
  nodes:
    - ip: 10.40.205.11
      percentage: 100
    - ip: 10.40.205.12
      percentage: 0
    - ip: 10.40.205.13
      percentage: 0
    - ip: 10.40.205.14
      percentage: 0
  workloads:
    - dapp: Ballot
      language: Solidity
      numOfRuns: 1
      rateControl: 50
      params:
        - ../target/performance-1.0-SNAPSHOT-jar-with-dependencies.jar    #executable
        - --concord           #use concord
        - 10.40.205.11       #concordIP
        - 100                #threadCount
        - ../data/proposals   #input data
    - dapp: Ballot
      language: Solidity
      numOfRuns: 1
      params:
          - ../target/performance-1.0-SNAPSHOT-jar-with-dependencies.jar  #executable
          - --concord             #use helen
          - 10.40.205.12       #helenIP
          - 100                #threadcount
          - ../data/proposals   #input data
  sleepTime: 10000
  outputDir: ./perf_result

advancedConfig:
  esxtop: nop
  #numberThreads: 0 #0 or undefined is default
  #concordUsername: admin@blockchain.local #this is optional
  #concordPassword: Admin!23 # this optional

#java -Xmx1g -jar ../target/performance-1.0-SNAPSHOT-jar-with-dependencies.jar --concord 10.40.205.133 500 ../data/proposals ./perf_result/wordload0
