---
simpleConfig:
  blockchain: concord #concord or etheruem
  environment: onprem
  nodeCount: 4
  port: 8545
  nodes:
    - ip: 10.40.205.11
      percentage: 100
    - ip: 10.40.205.12
      percentage: 0
    - ip: 10.40.205.13
      percentage: 0
    - ip: 10.40.205.14
      percentage: 0
  workloads:
    - dapp: Ballot
      language: Solidity
      numOfRuns: 1
      rateControl: 50
      params:
        - ../target/performance-1.0-SNAPSHOT-jar-with-dependencies.jar    #executable
        - --concord           #use concord, helen, or ethereum
        - 10.40.205.11       #concordIP, helenIP, or ethereumIP
        - 100                #numberVotes
        - ../data/proposals   #input data
    - dapp: Ballot
      language: Solidity
      numOfRuns: 1
      params:
          - ../target/performance-1.0-SNAPSHOT-jar-with-dependencies.jar  #executable
          - --concord             #use concord, helen, or ethereum
          - 10.40.205.12       #concordIP, helenIP, or ethereumIP
          - 100                #numberVotes
          - ../data/proposals   #input data
  sleepTime: 10000
  outputDir: ./perf_result

advancedConfig:
  esxtopCommand:
    - [prme-awperf-a009, abc@omdf] #hostnames
    - [root, root2] #usernames
    - [ca$hc0w, cfjrfv] #passwords
    - /vmfs/volumes/5b6c1162-9e8767c6-6315-246e96d05bec/datahl/ethConcor-esxtop-result-timestamp.csv #path for saving esxtop results
    - -a
    - -b
    - -d 3
    - -n 14000
  numberThreads: 0 #0 or undefined is default
  concordUsername: admin@blockchain.local #this is optional
  concordPassword: Admin!23 # this optional

#java -Xmx1g -jar ../target/performance-1.0-SNAPSHOT-jar-with-dependencies.jar --concord 10.40.205.133 500 ../data/proposals ./perf_result/wordload0
