simpleConfig:
  blockchain: concord #concord, etheruem, or quorum
  environment: onprem
  nodeCount: 4
  port: 8545
  http: false
  nodes:
    - ip: 10.40.205.101
      percentage: 100
      username: kubo
      password: Ponies!23
    - ip: 10.40.205.102
      percentage: 0
      username: kubo
      password: Ponies!23
    - ip: 10.40.205.103
      percentage: 0
      username: kubo
      password: Ponies!23
    - ip: 10.40.205.104
      percentage: 0
      username: kubo
      password: Ponies!23
  workloads:
    - dapp: Ballot
      language: Solidity
      numOfRuns: 1
      rateControl: 200
      logging: false
      params:
        - ../target/performance-1.0-SNAPSHOT-jar-with-dependencies.jar    #executable
        - --concord           #use concord, helen, or ethereum
        - 10.40.205.101       #concordIP, helenIP, or ethereumIP
        - 1000                #numberVotes
        - ../data/proposals   #input data
  sleepTime: 1000
  outputDir: ./perf_result

advancedConfig:
  dockerStats: false
  esxTop: true
  esxtopCommand:
    - [prme-awperf-a009, abc@omdf] #hostnames
    - [root, root2] #usernames
    - [ca$hc0w, cfjrfv] #passwords
    - /vmfs/volumes/5b6c1162-9e8767c6-6315-246e96d05bec/datahl/ethConcor-esxtop-result-timestamp.csv #path for saving esxtop results
    - -a
    - -b
    - -d 3
    - -n 14000
  numberThreads: 4 #0 or undefined is default
  concordUsername: admin@blockchain.local #this is optional
  concordPassword: Admin!23 # this optional

#java -Xmx1g -jar ../target/performance-1.0-SNAPSHOT-jar-with-dependencies.jar --concord 10.40.205.133 500 ../data/proposals ./perf_result/wordload0
