simpleConfig:
  blockchain: concord #concord, etheruem, or quorum
  environment: onprem
  nodeCount: 4
  port: 8545
  http: false
  nodes:
    - ip: 10.40.205.101
      percentage: 100
      username: username
      password: password
    - ip: 10.40.205.102
      percentage: 0
      username: username
      password: password
    - ip: 10.40.205.103
      percentage: 0
      username: username
      password: password
    - ip: 10.40.205.104
      percentage: 0
      username: username
      password: password
  workloads:
    - dapp: IOU
      language: DAML
      numOfRuns: 1
      rateControl: 0
      logging: false
      params:
        - 6865 #ledgerPort
        - Alice #party
        - 10 #numOfTrasactions
  sleepTime: 1000
  outputDir: ./perf_result

advancedConfig:
  dockerStats: false
  esxTop: false
  esxtopCommand:
    - [prme-awperf-a009] #hostnames
    - [username] #usernames
    - [password] #passwords
    - /vmfs/volumes/5b6c1162-9e8767c6-6315-246e96d05bec/datahl/ethConcor-esxtop-result-timestamp.csv #path for saving esxtop results
    - -a
    - -b
    - -d 3
    - -n 14000
  numberThreads: 4 #0 or undefined is default
  concordUsername: concordUsername #this is optional
  concordPassword: concordPassword # this optional

#java -Xmx1g -jar ../target/performance-1.0-SNAPSHOT-jar-with-dependencies.jar --concord 10.40.205.133 500 ../data/proposals ./perf_result/wordload0
