# pre-deploy the QuickStart DApp from DAML website (https://docs.daml.com/getting-started/quickstart.html)
# example:  daml deploy --host=10.40.205.67 --port=6865

simpleConfig:
  blockchain: concord #concord, etheruem, or quorum
  environment: onprem
  nodeCount: 4
  port: 6865
  http: true
  nodes:
    - ip: 10.158.161.42
      percentage: 100
    - ip: 10.40.205.82
      percentage: 0
    - ip: 10.40.205.83
      percentage: 0
    - ip: 10.40.205.84
      percentage: 0
  workloads:
    - dapp: IOU
      language: DAML
      numOfRuns: 1
      rateControl: 0
      logging: false
      params:
        - Alice #party
        - 10 #numOfTrasactions
  sleepTime: 1000
  numberThreads: 4 #0 or undefined is default
  outputDir: ./perf_result

advancedConfig:
  wavefront:
    enabled: true
    proxyHost: 10.40.205.202
    metricsPort: 2878
    source:  blockchain-benchmark
