version: "2"
services:
  helen:
    image: helen:latest
    ports:
    - 8080:8080
    volumes:
      - ./application.properties:/application.properties
  db-server:
    image: cockroachdb/cockroach:v2.0.2
    ports:
    - 26257:26257
    volumes:
    - ./cockroachDB:/cockroach/cockroach-data
    command:
    - start
    - --insecure